// app/photos/page.tsx
import { FacebookLogo, InstagramLogo, TwitterLogo, YoutubeLogo } from '@/components/BrandLogos'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: '@photosbydrevan',
  description: `Capturing this beautiful universe one photo at a time. 📸 Check out my photos and follow me on social media. 🤩`,
  alternates: {
    canonical: '/photos',
  },
};

export default function Photos() {
  return (
    <>
      <article className="max-w-4xl">
        <h1 className="text-xl sm:text-2xl text-purple-600">@photosbydrevan</h1>
        <h2
          className="text-5xl sm:text-6xl text-neutral-700 sm:leading-[1.1em] font-semibold"
        >
          Capturing this <span className="text-cyan-600 font-semibold"
            >beautiful universe</span
          > one photo at a time
        </h2>

        <h2 className="text-sm mt-8 text-purple-600 uppercase">Follow me on</h2>
        <div className="flex mt-1 space-x-5">
          <a
            href="https://www.facebook.com/photosbydrevan"
            target="_blank"
            rel="noopener"
          >
            <FacebookLogo className="h-10 w-auto" />
          </a>
          <a
            href="https://www.instagram.com/photosbydrevan/"
            target="_blank"
            rel="noopener"
          >
            <InstagramLogo className="h-10 w-auto" />
          </a>
          <a
            href="https://twitter.com/photosbydrevan"
            target="_blank"
            rel="noopener"
          >
            <TwitterLogo className="h-10 w-auto" />
          </a>
          <a
            href="https://www.youtube.com/@photosbydrevan"
            target="_blank"
            rel="noopener"
          >
            <YoutubeLogo className="h-10 w-auto" />
          </a>
        </div>
    </article>
    </>
  )
}

// apps/drevan.me/pages/photos.vue
<script setup lang="ts">
useSeoMeta({
  title: "@photosbydrevan",
  description:
    "Capturing this beautiful universe one photo at a time. 📸 Check out my photos and follow me on social media. 🤩",
});
</script>

<template>
  <div class="flex justify-center items-center min-h-screen">
    <article class="max-w-4xl">
      <h1 class="text-xl sm:text-2xl text-persian">@photosbydrevan</h1>
      <h2 class="text-5xl sm:text-6xl sm:leading-[1.1em] font-medium">
        Capturing this
        <span class="text-persian font-semibold">beautiful universe</span> one
        photo at a time
      </h2>

      <h2 class="text-sm mt-8 uppercase">Follow me on</h2>
      <div class="flex mt-1 space-x-5">
        <a
          href="https://www.facebook.com/photosbydrevan"
          target="_blank"
          rel="noopener"
        >
          <ColourfulBrandLogoFacebook class="h-10 w-auto" />
        </a>
        <a
          href="https://www.instagram.com/photosbydrevan/"
          target="_blank"
          rel="noopener"
        >
          <ColourfulBrandLogoInstagram class="h-10 w-auto" />
        </a>
        <a
          href="https://twitter.com/photosbydrevan"
          target="_blank"
          rel="noopener"
        >
          <ColourfulBrandLogoTwitter class="h-10 w-auto" />
        </a>
        <a
          href="https://www.youtube.com/@photosbydrevan"
          target="_blank"
          rel="noopener"
        >
          <ColourfulBrandLogoYoutube class="h-10 w-auto" />
        </a>
      </div>
    </article>
  </div>
</template>
